# Generated by Django 5.0 on 2024-01-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0002_rename_dapilkabkota_kecamatan_dapil_kabkota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provinsi',
            name='dapil_dpr',
        ),
        migrations.RemoveField(
            model_name='provinsi',
            name='dapil_dprdprov',
        ),
    ]
