# Generated by Django 5.0 on 2024-01-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0003_remove_provinsi_dapil_dpr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kabkota',
            old_name='dapil_dprdkabkota',
            new_name='dapil_dpr',
        ),
    ]
