# Generated by Django 5.0 on 2024-01-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0004_rename_dapil_dprdkabkota_kabkota_dapil_dpr'),
    ]

    operations = [
        migrations.AddField(
            model_name='tps',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tps',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
