# Generated by Django 5.0 on 2024-02-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0005_tps_latitude_tps_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tps',
            name='no',
            field=models.IntegerField(max_length=3),
        ),
    ]
