# Generated by Django 5.0 on 2024-02-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0009_alter_tps_latitude_alter_tps_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tps',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tps',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
