# Generated by Django 5.0 on 2024-02-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0010_alter_tps_latitude_alter_tps_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tps',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='tps',
            old_name='longitude',
            new_name='lon',
        ),
    ]
