# Generated by Django 5.0 on 2024-02-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0011_rename_latitude_tps_lat_rename_longitude_tps_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tps',
            old_name='lon',
            new_name='lng',
        ),
    ]
