# Generated by Django 5.0 on 2024-02-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0012_rename_lon_tps_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tps',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tps',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
