# Generated by Django 5.0 on 2024-02-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0013_alter_tps_lat_alter_tps_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tps',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tps',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
