# Generated by Django 5.0 on 2024-02-02 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wilayah', '0005_tps_latitude_tps_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarPemilih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('rt', models.CharField(blank=True, max_length=3, null=True)),
                ('rw', models.CharField(blank=True, max_length=3, null=True)),
                ('desa', models.CharField(blank=True, max_length=50, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=50, null=True)),
                ('kabupaten', models.CharField(blank=True, max_length=50, null=True)),
                ('provinsi', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wilayah.tps')),
            ],
        ),
    ]
