# Generated by Django 5.0 on 2024-01-06 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wilayah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DapilDpr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('jumlah_kursi', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provinsi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dapildpr_provinsi', to='wilayah.provinsi')),
                ('wilayah', models.ManyToManyField(blank=True, related_name='dapildpr_wilayah', to='wilayah.provinsi')),
            ],
        ),
        migrations.CreateModel(
            name='DapilDprdKabKota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('jumlah_kursi', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kabkota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dapildprdkabkota_kabkota', to='wilayah.kabkota')),
                ('provinsi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dapildprdkabkota_provinsi', to='wilayah.provinsi')),
                ('wilayah', models.ManyToManyField(blank=True, related_name='dapildprdkabkota_wilayah', to='wilayah.kecamatan')),
            ],
        ),
        migrations.CreateModel(
            name='DapilDprdProv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('jumlah_kursi', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provinsi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dapildprdprov_provinsi', to='wilayah.provinsi')),
                ('wilayah', models.ManyToManyField(blank=True, related_name='dapildprdprov_wilayah', to='wilayah.provinsi')),
            ],
        ),
    ]
