# Generated by Django 5.0 on 2024-01-06 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daerah_pemilihan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dapildprdprov',
            name='provinsi',
        ),
        migrations.RemoveField(
            model_name='dapildprdprov',
            name='wilayah',
        ),
        migrations.DeleteModel(
            name='DapilDpr',
        ),
        migrations.DeleteModel(
            name='DapilDprdProv',
        ),
    ]
