# Generated by Django 5.0 on 2024-01-30 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lhp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahapan', models.IntegerField(blank=True, choices=[(1, 'Masa Tenang'), (2, 'Persiapan Pemungutan Suara'), (3, 'Pemungutan dan Penghitungan Suara'), (3, 'Pengawasan Lainnya')], null=True)),
                ('bentuk', models.IntegerField(blank=True, choices=[(1, 'Langsung'), (2, 'Tidak Langsung')], null=True)),
                ('tujuan', models.CharField(blank=True, max_length=255, null=True)),
                ('sasaran', models.CharField(blank=True, max_length=255, null=True)),
                ('waktu', models.CharField(blank=True, max_length=255, null=True)),
                ('tempat', models.CharField(blank=True, max_length=255, null=True)),
                ('uraian', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
