# Generated by Django 5.0 on 2024-01-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporanhasil', '0002_alter_lhp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lhp',
            name='bentuk',
            field=models.IntegerField(choices=[(1, 'Langsung'), (2, 'Tidak Langsung')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lhp',
            name='sasaran',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lhp',
            name='tahapan',
            field=models.IntegerField(choices=[(1, 'Masa Tenang'), (2, 'Persiapan Pemungutan Suara'), (3, 'Pemungutan dan Penghitungan Suara'), (3, 'Pengawasan Lainnya')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lhp',
            name='tempat',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lhp',
            name='tujuan',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lhp',
            name='waktu',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
