# Generated by Django 5.0 on 2024-01-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporanhasil', '0003_alter_lhp_bentuk_alter_lhp_sasaran_alter_lhp_tahapan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lhp',
            name='uraian',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
