# Generated by Django 5.0 on 2024-01-30 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporanhasil', '0004_alter_lhp_uraian'),
    ]

    operations = [
        migrations.CreateModel(
            name='LhpMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='lhp/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='laporanhasil.lhp')),
            ],
        ),
    ]
