# Generated by Django 5.0 on 2024-01-31 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporanhasil', '0005_lhpmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lhpmedia',
            old_name='post',
            new_name='lhp',
        ),
    ]
