# Generated by Django 5.0 on 2024-01-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporanhasil', '0007_remove_lhp_bentuk_remove_lhp_sasaran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lhp',
            name='sasaran',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lhp',
            name='tempat',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lhp',
            name='uraian',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lhp',
            name='waktu',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
