# Generated by Django 5.0 on 2024-01-31 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporanhasil', '0008_lhp_sasaran_lhp_tempat_lhp_uraian_lhp_waktu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lhp',
            name='bentuk',
            field=models.IntegerField(choices=[(1, 'Langsung'), (2, 'Tidak Langsung')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lhp',
            name='tahapan',
            field=models.IntegerField(choices=[(1, 'Masa Tenang'), (2, 'Persiapan Pemungutan Suara'), (3, 'Pemungutan dan Penghitungan Suara'), (3, 'Pengawasan Lainnya')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lhp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
