# Generated by Django 5.0 on 2024-01-06 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daerah_pemilihan', '0001_initial'),
        ('wilayah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parpol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('akronim', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DprRi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('no_urut', models.IntegerField()),
                ('dapil', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto-caleg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wilayah.provinsi')),
                ('parpol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peserta_pemilu.parpol')),
            ],
        ),
        migrations.CreateModel(
            name='DprdProv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('no_urut', models.IntegerField()),
                ('dapil', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto-caleg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wilayah.provinsi')),
                ('parpol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peserta_pemilu.parpol')),
            ],
        ),
        migrations.CreateModel(
            name='DprdKabKota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('no_urut', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto-caleg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dapil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daerah_pemilihan.dapildprdkabkota')),
                ('kabkota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wilayah.kabkota')),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wilayah.provinsi')),
                ('parpol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dprdkabkota', to='peserta_pemilu.parpol')),
            ],
        ),
    ]
