# Generated by Django 5.0 on 2024-01-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peserta_pemilu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dprri',
            name='parpol',
        ),
        migrations.RemoveField(
            model_name='dprri',
            name='provinsi',
        ),
        migrations.DeleteModel(
            name='DprdProv',
        ),
        migrations.DeleteModel(
            name='DprRi',
        ),
    ]
