# Generated by Django 5.0 on 2024-01-06 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peserta_pemilu', '0001_initial'),
        ('wilayah', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuaraPeserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suara', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_caleg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peserta_pemilu.dprdkabkota')),
                ('tps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.tps')),
            ],
        ),
        migrations.CreateModel(
            name='SuaraTps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pemilih_dpt_lk', models.IntegerField(blank=True, default=0, null=True)),
                ('pemilih_dpt_pm', models.IntegerField(blank=True, default=0, null=True)),
                ('pengguna_dpt_lk', models.IntegerField(blank=True, default=0, null=True)),
                ('pengguna_dpt_pm', models.IntegerField(blank=True, default=0, null=True)),
                ('pengguna_dptb_lk', models.IntegerField(blank=True, default=0, null=True)),
                ('pengguna_dptb_pm', models.IntegerField(blank=True, default=0, null=True)),
                ('pengguna_dpk_lk', models.IntegerField(blank=True, default=0, null=True)),
                ('pengguna_dpk_pm', models.IntegerField(blank=True, default=0, null=True)),
                ('jml_terima', models.IntegerField(blank=True, default=0, null=True)),
                ('jml_digunakan', models.IntegerField(blank=True, default=0, null=True)),
                ('jml_dikembalikan', models.IntegerField(blank=True, default=0, null=True)),
                ('jml_tidakdigunakan', models.IntegerField(blank=True, default=0, null=True)),
                ('disabilitas_laki_laki', models.IntegerField(blank=True, default=0, null=True)),
                ('disabilitas_wanita', models.IntegerField(blank=True, default=0, null=True)),
                ('tps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.tps')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='suarapeserta',
            constraint=models.UniqueConstraint(fields=('tps',), name='unique_tps_constraint'),
        ),
    ]
