# Generated by Django 5.0 on 2024-02-02 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perolehansuara', '0001_initial'),
        ('wilayah', '0007_alter_tps_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilPwpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paslon1', models.IntegerField()),
                ('paslon2', models.IntegerField()),
                ('paslon3', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.tps')),
            ],
        ),
    ]
