# Generated by Django 5.0 on 2024-02-05 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_userpengawastps_userprofile'),
        ('perolehansuara', '0004_datadisabilitasppwp_ptps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadisabilitasppwp',
            name='tps',
        ),
        migrations.RemoveField(
            model_name='datapemilihpenggunahakpilihppwp',
            name='tps',
        ),
        migrations.RemoveField(
            model_name='datapenggunasuratsuarappwp',
            name='tps',
        ),
        migrations.RemoveField(
            model_name='datasuarasahdantidaksahppwp',
            name='tps',
        ),
        migrations.RemoveField(
            model_name='hasilppwp',
            name='tps',
        ),
        migrations.CreateModel(
            name='UploadPpwp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='ppwp/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ptps', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userpengawastps')),
            ],
        ),
    ]
