# Generated by Django 5.0 on 2024-02-05 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_userpengawastps_userprofile'),
        ('perolehansuara', '0006_remove_uploadppwp_ptps_uploadppwp_hasil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadppwp',
            name='hasil',
        ),
        migrations.AddField(
            model_name='uploadppwp',
            name='ptps',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.userpengawastps'),
        ),
    ]
