# Generated by Django 5.0 on 2024-02-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_userpengawastps_userprofile'),
        ('perolehansuara', '0007_remove_uploadppwp_hasil_uploadppwp_ptps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadPpwp',
            new_name='PpwpMedia',
        ),
    ]
