# Generated by Django 5.0 on 2024-02-06 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_userpengawastps_userprofile'),
        ('perolehansuara', '0011_cekppwp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpdRiMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='dpd/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ptps', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.userpengawastps')),
            ],
        ),
        migrations.CreateModel(
            name='DprdKabMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='dprdkab/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ptps', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.userpengawastps')),
            ],
        ),
        migrations.CreateModel(
            name='DprdProvMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='dprdprov/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ptps', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.userpengawastps')),
            ],
        ),
        migrations.CreateModel(
            name='DprRiMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='dpr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ptps', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.userpengawastps')),
            ],
        ),
    ]
