# Generated by Django 5.0 on 2024-02-06 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_userpengawastps_userprofile'),
        ('perolehansuara', '0012_dpdrimedia_dprdkabmedia_dprdprovmedia_dprrimedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CekDpdRi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perolehansuara.dpdrimedia')),
            ],
        ),
        migrations.RenameModel(
            old_name='DprdKabMedia',
            new_name='DprdKabKotaMedia',
        ),
        migrations.CreateModel(
            name='CekDprdKabKota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perolehansuara.dprdkabkotamedia')),
            ],
        ),
        migrations.CreateModel(
            name='CekDprdProv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perolehansuara.dprdprovmedia')),
            ],
        ),
        migrations.CreateModel(
            name='CekDprRi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perolehansuara.dprrimedia')),
            ],
        ),
    ]
