# Generated by Django 5.0 on 2024-02-06 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_userprofile_user'),
        ('perolehansuara', '0013_cekdpdri_rename_dprdkabmedia_dprdkabkotamedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppwpmedia',
            name='ptps',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ppwp', to='accounts.userpengawastps'),
        ),
    ]
