# Generated by Django 5.0 on 2024-01-06 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daerah_pemilihan', '0001_initial'),
        ('wilayah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('role', models.IntegerField(choices=[(1, 'Calon Legislatif'), (2, 'Saksi TPS')], default=2)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCaleg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dapil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daerah_pemilihan.dapildprdkabkota')),
                ('kabkota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.kabkota')),
                ('provinsi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.provinsi')),
                ('user', models.OneToOneField(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSaksiTps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caleg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caleg', to=settings.AUTH_USER_MODEL)),
                ('kabkota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.kabkota')),
                ('kecamatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.kecamatan')),
                ('keldesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.keldesa')),
                ('provinsi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.provinsi')),
                ('tps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.tps')),
                ('user', models.OneToOneField(limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
