# Generated by Django 5.0 on 2024-01-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Bawaslu'), (2, 'Pengawas TPS')], default=2),
        ),
    ]
