# Generated by Django 5.0 on 2024-02-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_whetherreport_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whetherreport',
            name='user_profile',
        ),
    ]
