# Generated by Django 5.0 on 2024-02-03 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_whetherreport_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whetherreport',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whetherreport',
            name='user_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='accounts.userprofile'),
            preserve_default=False,
        ),
    ]
