# Generated by Django 5.0 on 2024-02-03 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_whetherreport_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whetherreport',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='accounts.userprofile'),
        ),
    ]
