# Generated by Django 5.0 on 2024-02-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_whetherreport_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wa',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
