# Generated by Django 5.0 on 2024-02-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userpengawastps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='kabkota',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='kecamatan',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='keldesa',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='provinsi',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tps',
        ),
    ]
