# Generated by Django 5.0 on 2024-02-04 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_userprofile_kabkota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whetherreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='whetherreport',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='whetherreport',
            name='ptps',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ptps', to='accounts.userpengawastps'),
            preserve_default=False,
        ),
    ]
