# Generated by Django 5.0 on 2024-02-04 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_whetherreport_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whetherreport',
            name='ptps',
        ),
        migrations.AddField(
            model_name='whetherreport',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.userpengawastps'),
            preserve_default=False,
        ),
    ]
