# Generated by Django 5.0 on 2024-02-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_user_endreport_ptps_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endreport',
            old_name='ptps',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='startreport',
            old_name='ptps',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='whetherreport',
            old_name='ptps',
            new_name='user',
        ),
    ]
