# Generated by Django 5.0 on 2024-02-04 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_endreport_ptps_startreport_ptps_whetherreport_ptps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endreport',
            name='ptps',
        ),
        migrations.RemoveField(
            model_name='startreport',
            name='ptps',
        ),
        migrations.RemoveField(
            model_name='whetherreport',
            name='ptps',
        ),
        migrations.AlterField(
            model_name='endreport',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userpengawastps'),
        ),
        migrations.AlterField(
            model_name='startreport',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userpengawastps'),
        ),
        migrations.AlterField(
            model_name='whetherreport',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userpengawastps'),
        ),
    ]
