# Generated by Django 5.0 on 2024-02-04 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_endreport_ptps_startreport_ptps_whetherreport_ptps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpengawastps',
            name='maker',
            field=models.ForeignKey(limit_choices_to={'role': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maker', to=settings.AUTH_USER_MODEL),
        ),
    ]
