# Generated by Django 5.0 on 2024-02-04 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_endreport_ptps_startreport_ptps_whetherreport_ptps'),
        ('wilayah', '0014_alter_tps_lat_alter_tps_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpengawastps',
            name='kabkota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.kabkota'),
        ),
        migrations.AlterField(
            model_name='userpengawastps',
            name='kecamatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.kecamatan'),
        ),
        migrations.AlterField(
            model_name='userpengawastps',
            name='keldesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.keldesa'),
        ),
        migrations.AlterField(
            model_name='userpengawastps',
            name='provinsi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.provinsi'),
        ),
        migrations.AlterField(
            model_name='userpengawastps',
            name='tps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayah.tps'),
        ),
    ]
