# Generated by Django 5.0 on 2024-02-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_userpengawastps_kabkota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endreport',
            name='ptps',
        ),
        migrations.RemoveField(
            model_name='startreport',
            name='ptps',
        ),
        migrations.RemoveField(
            model_name='whetherreport',
            name='ptps',
        ),
    ]
