# Generated by Django 5.0 on 2024-02-04 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_rename_user_endreport_ptps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpengawastps',
            name='userprofile',
            field=models.OneToOneField(limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile'),
        ),
    ]
