# Generated by Django 5.0 on 2024-02-04 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_userpengawastps_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpengawastps',
            name='userprofile',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile'),
        ),
    ]
