# Generated by Django 5.0 on 2024-02-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_userpengawastps_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jk',
            field=models.IntegerField(blank=True, choices=[(1, 'Laki-laki'), (2, 'Perempuan')], null=True),
        ),
    ]
