# Generated by Django 5.0 on 2024-02-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_userprofile_rt_userprofile_rw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rt',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rw',
            field=models.CharField(blank=True, null=True),
        ),
    ]
